### PR TITLE
adds query and queryAll to found nodes

### PR DESCRIPTION
**Pull request by DaKaZ**
We ran into a situation where we needed to query some found results.  Imagine you have a structure that looks roughly like this (simplified):
```
...
<Picker testID="yearPicker">
  <Item>2019</Item>
  <Item>2020</Item>
  <Item>2021</Item>
</Picker>
```
With this PR you can:
```
const items = view.query('#yearPicker').queryAll('Item');
expect(items.map((item) => item.text()).toEqual(expect.arrayMatching(['2019', '2020', '2021']);
```

### CODE REVIEW

**Comment by shouse** [comment]
So I went to my mentor @DaKaZ with an issue and he came up with this solution.  @shichongrui This really improves the lib capability.  I'm running with a work around that doesn't look as good and doesn't use this lib.  I would **vastly** prefer to use this syntax.  I think it provides a multitude of benefits.

**Comment by shichongrui** [comment]
I like it. Can you add some tests to `index.spec.js`?

**Comment by DaKaZ** [comment]
@shichongrui I added tests, but frankly none of your tests work on my machine.  They all run, but they are bad.  For example, see line 98 where I added the test for text on one of your existing tests, this was green until I added that line.  Turns out the return from query was `undefined`, but that passed the `not.toBeNull`. See here:
```
  it('will match a testID', () => {
    let view = renderer(<Text testID='test'>Yo</Text>)
    let text = view.query('#test')
    expect(text).not.toBeNull()
    expect(text.text()).toEqual('Yo')
  })
```

**Comment by shichongrui** [comment]
My team moved away from this to using enzyme and then dropped react native all together so I don't do much react native anymore. I'm willing to accept pull requests for the test issues or if someone who uses this library and benefits from it would like to take it over I'm happy to hand it over to someone else. Your test looks good and I'll merge and do a release.

**Comment by shichongrui** [comment]
Nevermind, I pulled down the changes and found that the new test didn't pass and when investigating why, it looked like this code change was just missing one thing. Added that, fixed the tests and am doing a release.

**Pull request merged**
